import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {escapeHTML,formatTime,timeLabel,clamp,validateCatalog,getFilteredTracks,nextTrackId,artwork} from '../core.js';
const catalog=JSON.parse(fs.readFileSync(new URL('../data/catalog.json',import.meta.url),'utf8'));
const tracks=catalog.tracks;
test('catalog validates with completed tracks and exact relative asset paths',()=>{assert.equal(validateCatalog(catalog),catalog);assert.ok(tracks.length>=38);});
test('formatted duration handles NaN, negatives and fractional values',()=>{assert.equal(formatTime(125.99),'2:05');assert.equal(formatTime(-4),'0:00');assert.equal(formatTime(NaN),'0:00');assert.equal(timeLabel(125),'2 分 5 秒');});
test('HTML escaping protects titles, attributes and notes',()=>{assert.equal(escapeHTML('<a "x" & \'y\'>'),'&lt;a &quot;x&quot; &amp; &#39;y&#39;&gt;');});
test('catalog rejects absolute or traversal audio paths',()=>{for(const src of ['/audio/a.mp3','../a.mp3','https://example.com/a.mp3']){const copy=structuredClone(catalog);copy.tracks[0].src=src;assert.throws(()=>validateCatalog(copy));}});
test('catalog rejects duplicate IDs and missing data',()=>{const copy=structuredClone(catalog);copy.tracks.push(copy.tracks[0]);assert.throws(()=>validateCatalog(copy));assert.throws(()=>validateCatalog({tracks:[]}));});
test('cover artwork has multiple original variants and safe SVG',()=>{const art=tracks.map(t=>artwork(t));assert.ok(new Set(art).size>=8);assert.ok(art.every(svg=>svg.includes('aria-hidden="true"')&&!svg.includes('<script')));});
test('search supports Chinese title and English terms',()=>{assert.equal(getFilteredTracks(tracks,{query:'雨落楼梯口'})[0].id,'jazz_waltz');assert.ok(getFilteredTracks(tracks,{query:'NEO-SOUL'}).length>=3);});
test('search matches all separate words',()=>{assert.equal(getFilteredTracks(tracks,{query:'Rain Landing'})[0].id,'jazz_waltz');assert.equal(getFilteredTracks(tracks,{query:'totally-nonexistent'}).length,0);});
test('style and series filters intersect without changing original array',()=>{const before=tracks.map(t=>t.id);const result=getFilteredTracks(tracks,{group:'sketch',style:'爵士'});assert.equal(result.length,1);assert.equal(result[0].id,'jazz_waltz');assert.deepEqual(tracks.map(t=>t.id),before);});
test('all 3 collection groups are present',()=>{assert.deepEqual([...new Set(tracks.map(t=>t.group))].sort(),['acoustic','electronic','sketch']);assert.equal(tracks.filter(t=>t.group==='sketch').length,10);});
test('duration sorting is numeric in both directions',()=>{const ascending=getFilteredTracks(tracks,{sort:'duration-asc'}),descending=getFilteredTracks(tracks,{sort:'duration-desc'});assert.ok(ascending.every((t,i)=>!i||t.durationSeconds>=ascending[i-1].durationSeconds));assert.equal(ascending[0].id,descending.at(-1).id);});
test('next track handles beginning, end, wrapping and empty queues',()=>{assert.equal(nextTrackId(['a','b'],'a'),'b');assert.equal(nextTrackId(['a','b'],'b',1,false),null);assert.equal(nextTrackId(['a','b'],'b'),'a');assert.equal(nextTrackId(['a','b'],'a',-1),'b');assert.equal(nextTrackId([],'a'),null);assert.equal(nextTrackId(['a','b'],'x'),'a');});
test('clamp bounds volume and seeking',()=>{assert.equal(clamp(2,0,1),1);assert.equal(clamp(-1,0,1),0);assert.equal(clamp(.4,0,1),.4);});
test('every track has grounded Chinese editorial and recorded revisions',()=>{for(const t of tracks){assert.match(t.story,/[\u3400-\u9fff]/u);assert.ok(t.revisions.length>=2);assert.equal(t.revisions.length,t.revisionRounds);assert.equal(t.reaperVerified,true);assert.match(t.projectDisclosure,/不含(?:现成)?(?:音频|钢琴)分轨/);}});
test('final corrections remain distinct from the two substantive rounds',()=>{for(const id of ['neo_soul','synthwave']){const t=tracks.find(t=>t.id===id);assert.equal(t.finalVersion,'v4');assert.equal(t.reaperVersions,4);assert.equal(t.revisionLabel,'2 轮 + 终校');assert.match(t.revisions.at(-1).version,/终校/);}});

test('sample-based stories disclose sources and pending listening review honestly',()=>{const stories=tracks.filter(t=>t.collection==='story-collection-20261006');assert.ok(stories.length>=4);for(const t of stories){assert.equal(t.provenance.thirdPartySamples,true);assert.equal(t.provenance.auditoryReview,false);assert.match(t.soundSourceZh,/采样/);assert.match(t.compositionNotes,/Moonlight|Iowa/);assert.match(t.provenance.sampleLicense,/CC BY|Iowa/);assert.ok(t.revisions.length>=2);}});
